# Sexual violence in different states

TLDR: there's not that relates to consent directly

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

dataloc = "..//data//processed//"
manualloc = "..//data//manual//"

infile_str = dataloc + "etl_5_yrbs.csv"

survey = pd.read_csv(infile_str)

In [2]:
survey.head()

,Unnamed: 0,sitecode,year,weight,stratum,PSU,age,q19,q20,q21,q22,qtaughtsexed,qtaughtstd,qtaughtcondom,qtaughtbc
0,0,AL,1991,98.1638,8,2,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,AL,1991,69.1663,15,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,AL,1991,80.3232,15,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,AL,1991,66.5061,20,2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,AL,1991,89.3992,5,1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# how complete is the data
survey.count()

Unnamed: 0       1530390
sitecode         1530390
year             1530390
weight           1530390
stratum          1530390
PSU              1530390
age              1530390
q19              1056738
q20               219729
q21               506910
q22               698977
qtaughtsexed       27747
qtaughtstd         16545
qtaughtcondom          0
qtaughtbc          15277
dtype: int64

## Basic tabulations of the survey questions

Q19 "Forced sexual intercourse"
1. "Yes"
2. "No"
/

Q20 "Sexual violence"
1. "0 times"
2. "1 time"
3. "2 or 3 times"
4. "4 or 5 times"
5. "6 or more times"
/

Q21 "Sexual dating violence"
1. "Did not date"
2. "0 times"
3. "1 time"
4. "2 or 3 times"
5. "4 or 5 times"
6. "6 or more times"
/

Q22 "Physical dating violence"
1. "Did not date"
2. "0 times"
3. "1 time"
4. "2 or 3 times"
5. "4 or 5 times"
6. "6 or more times"
/

In [4]:
survey.q19.value_counts()

2.0    965142
1.0     91596
Name: q19, dtype: int64

In [5]:
survey.q20.value_counts()

1.0    194903
2.0     12344
3.0      7222
5.0      3251
4.0      2009
Name: q20, dtype: int64

In [6]:
survey.q21.value_counts()

2.0    298442
1.0    176188
3.0     13555
4.0      9478
6.0      6549
5.0      2698
Name: q21, dtype: int64

In [7]:
survey.q22.value_counts()

2.0    408680
1.0    246963
3.0     17380
4.0     12560
6.0      9514
5.0      3880
Name: q22, dtype: int64

## Basic tabulation of sex ed q's

qtaughtsexed
1. "Yes"
2. "No"
3. "Not sure"
/

qtaughtstd
1. "Yes"
2. "No"
3. "Not sure"
/

qtaughtcondom
1. "Yes"
2. "No"
3. "Not sure"
/

qtaughtbc
1. "Yes"
2. "No"
3. "Not sure"

In [8]:
survey.columns

Index(['Unnamed: 0', 'sitecode', 'year', 'weight', 'stratum', 'PSU', 'age',
       'q19', 'q20', 'q21', 'q22', 'qtaughtsexed', 'qtaughtstd',
       'qtaughtcondom', 'qtaughtbc'],
      dtype='object')

In [9]:
survey.qtaughtsexed.value_counts()

1.0    21118
2.0     4970
3.0     1659
Name: qtaughtsexed, dtype: int64

In [10]:
survey.qtaughtstd.value_counts()

1.0    13273
2.0     2377
3.0      895
Name: qtaughtstd, dtype: int64

In [11]:
survey.qtaughtcondom.value_counts()

Series([], Name: qtaughtcondom, dtype: int64)

In [12]:
survey.qtaughtbc.value_counts()

1.0    9971
2.0    4205
3.0    1101
Name: qtaughtbc, dtype: int64

## Actual analyses

First, recode all the questions so that 0 is no (or never) and 1 is yes (or at least once)

In [13]:
# q19
survey = survey.replace({'q19': 2}, 0)

# q20 
survey = survey.replace({'q20': 1}, 0)
survey = survey.replace({'q20': [2,3,4,5]}, 1)

# q21
survey = survey.replace({'q21': [1,2]}, 0)
survey = survey.replace({'q21': [3,4,5,6]}, 1)

# q22
survey = survey.replace({'q22': [1,2]}, 0)
survey = survey.replace({'q22': [3,4,5,6]}, 1)

In [16]:
print(survey.q19.mean())
print(survey.q20.mean())
print(survey.q21.mean())
print(survey.q22.mean())

0.08667806021927857
0.11298463106827046
0.0636799431851808
0.06199631747539618

In [21]:
# unweighted averages by state

survey.groupby("sitecode").mean()

,Unnamed: 0,year,weight,stratum,PSU,q19,q20,q21,q22,qtaughtsexed,qtaughtstd,qtaughtcondom,qtaughtbc
sitecode,,,,,,,,,,,,,
AK,328092.025552,2009.855076,22.000922,12.033249,2.629031,0.091249,0.124679,0.054963,0.053083,NaN,NaN,NaN,NaN
AL,153572.950815,2001.249571,95.969997,11.445367,1.517989,0.102685,0.114779,0.064978,0.075939,NaN,NaN,NaN,NaN
AR,275129.323865,2007.465937,75.023339,12.491364,1.667384,0.126390,0.158828,0.077991,0.090140,NaN,NaN,NaN,NaN
AZB,307921.111408,2010.023392,110.881344,14.598398,1.799220,0.102044,0.116331,0.049679,0.045951,NaN,NaN,NaN,NaN
CA,559744.353314,2016.759050,957.831319,7.300495,1.591098,0.071514,0.139258,0.064620,0.043259,NaN,NaN,NaN,NaN
CO,382522.700800,2012.048691,151.760417,8.681134,1.500068,0.064908,NaN,NaN,0.054559,NaN,NaN,NaN,NaN
CT,343814.683223,2010.736391,75.214991,11.300391,1.524935,0.078546,NaN,0.069354,0.049232,NaN,NaN,NaN,1.354379
DE,264008.540065,2008.098904,13.725101,14.806248,3.129393,0.078388,0.073110,0.055154,0.059928,NaN,NaN,NaN,NaN
FL,347182.736111,2010.784523,146.457716,18.113354,1.617216,0.077369,0.105736,0.062687,0.065124,NaN,NaN,NaN,NaN
GA,295339.724606,2007.387235,186.391779,11.206801,1.655478,0.104628,0.115958,0.034693,0.062711,1.278689,1.159924,NaN,NaN
HI,401777.950366,2011.443122,15.478294,13.449102,5.972546,0.092416,0.123862,0.065373,0.061841,NaN,1.286002,NaN,NaN
IA,352670.331656,2009.652150,98.862734,7.211949,1.542401,0.086451,0.113019,0.046451,0.051768,NaN,NaN,NaN,NaN
ID,224166.638741,2004.025790,36.364162,14.422391,1.735175,0.092139,0.143330,0.084063,0.057567,1.403949,NaN,NaN,NaN
IL,344715.440916,2008.940496,165.816746,20.236400,3.559924,0.093094,0.132078,0.058152,0.070475,1.221476,1.163558,NaN,1.318504
KS,380029.478484,2011.672894,76.702983,13.040352,1.614625,0.083661,0.123907,0.065763,0.047153,NaN,NaN,NaN,NaN
KY,331112.274670,2009.642736,86.192129,15.125063,1.641265,0.096787,0.097492,0.060976,0.065334,NaN,NaN,NaN,NaN
LA,267668.584115,2005.914321,102.646423,23.261961,1.656660,NaN,NaN,0.109229,0.102922,NaN,NaN,NaN,NaN
MD,549932.515854,2015.531222,9.896106,73.541147,10.642365,0.092912,0.112280,0.065322,0.068212,NaN,NaN,NaN,NaN
ME,444621.057309,2012.137094,11.433610,9.876580,3.019660,0.086361,NaN,NaN,0.058827,NaN,NaN,NaN,NaN
MI,329491.088798,2008.287078,129.555990,18.031267,1.766095,0.094117,0.120986,0.057554,0.055786,NaN,NaN,NaN,NaN
MO,256989.149353,2004.843535,142.319885,6.201760,1.511313,0.093341,NaN,NaN,0.072008,1.356846,NaN,NaN,NaN
MS,280275.724495,2005.960707,80.181600,9.597222,1.586818,0.099134,0.116676,0.074777,0.080601,1.412302,NaN,NaN,1.578348
MT,334313.853250,2007.667376,13.723201,15.840655,2.615956,0.096092,0.109962,0.063267,0.058439,NaN,NaN,NaN,NaN
NC,338516.299563,2008.553739,122.488438,15.581907,2.633102,0.089783,0.121273,0.063998,0.064490,1.165883,NaN,NaN,NaN
ND,341522.824449,2008.519606,18.284485,15.580638,2.049422,0.075958,0.095250,NaN,0.058333,1.349407,NaN,NaN,NaN
NE,280682.359593,2005.546951,35.176980,17.597082,2.036520,0.085800,0.100856,0.054627,0.046259,NaN,NaN,NaN,NaN
NH,503486.806829,2013.492928,11.996976,31.955128,8.220778,0.067918,0.102461,0.063501,0.052260,NaN,NaN,NaN,NaN
NJ,352170.654180,2009.091877,227.100058,7.362185,1.529476,0.087096,0.111994,NaN,0.046043,NaN,NaN,NaN,NaN
NM,437947.603416,2011.453568,17.532455,10.802648,1.948757,0.086166,0.108493,0.067384,0.064100,NaN,NaN,NaN,NaN
NV,283259.424371,2005.534442,60.467483,17.623786,1.704721,0.092930,0.102978,0.072505,0.059969,NaN,NaN,NaN,NaN
NY,398296.496987,2010.205385,78.347557,42.174102,2.349614,0.073151,0.107531,0.062385,0.062208,NaN,NaN,NaN,NaN
OK,427857.112436,2011.047559,106.169927,12.976687,1.569107,0.077990,0.110333,0.057913,0.053955,NaN,NaN,NaN,NaN
PA,575339.432930,2015.396642,196.345532,15.514714,1.528886,0.077935,0.101786,0.045107,0.047519,NaN,NaN,NaN,NaN
RI,392135.678295,2009.693126,18.907506,6.060201,1.629647,0.080153,NaN,0.064635,0.055489,NaN,NaN,NaN,1.460526
SC,180547.668798,2000.011832,69.135981,13.232943,1.558543,0.104379,0.132895,0.061121,0.066460,NaN,1.206468,NaN,1.457663
SD,265755.557322,2004.302158,26.856659,7.091539,1.782127,0.085702,0.119943,0.056883,0.052091,1.560400,NaN,NaN,NaN
TN,397051.358273,2009.110893,116.347209,10.706651,1.513089,0.085025,NaN,0.088656,0.076507,NaN,1.291019,NaN,NaN
TX,353516.892834,2008.275391,355.096979,19.243022,1.717690,0.090410,0.101644,0.058566,0.063146,NaN,NaN,NaN,NaN
UT,228597.626555,2001.833947,68.633856,14.797717,1.553930,0.081781,0.148570,0.064485,0.047338,NaN,NaN,NaN,NaN
VA,580484.333120,2015.285284,88.364226,19.457669,2.173025,0.057621,0.100222,0.044024,0.063333,NaN,NaN,NaN,NaN
VT,417547.899610,2009.099273,2.906372,15.075410,1.503869,0.061710,NaN,0.067390,0.049648,NaN,NaN,NaN,NaN
WI,331142.129073,2006.271782,121.303583,13.114954,1.502285,0.069261,NaN,0.075792,0.055419,NaN,NaN,NaN,NaN
WV,322924.307888,2005.477161,48.661975,9.261991,1.647619,0.097312,0.122710,0.064751,0.076822,NaN,NaN,NaN,NaN
WY,309983.067238,2005.875202,12.218449,15.204401,2.748746,0.114681,NaN,0.078225,0.074176,NaN,NaN,NaN,NaN

In [22]:
s_q19 = survey[~np.isnan(survey.q19)]
s_q20 = survey[~np.isnan(survey.q20)]
s_q21 = survey[~np.isnan(survey.q21)]
s_q22 = survey[~np.isnan(survey.q22)]

In [25]:
q19_w  = s_q19.groupby("sitecode").apply(lambda x: np.average(x.q19, weights = x.weight))
q20_w  = s_q20.groupby("sitecode").apply(lambda x: np.average(x.q20, weights = x.weight))
q21_w  = s_q21.groupby("sitecode").apply(lambda x: np.average(x.q21, weights = x.weight))
q22_w  = s_q22.groupby("sitecode").apply(lambda x: np.average(x.q22, weights = x.weight))

In [56]:
states = {
    'AK':'Alaska',
    'AL':'Alabama',
    'AR':'Arkansas',
    'AZB':'Arizona',
    'CA':'California',
    'CO':'Colorado',
    'CT':'Connecticut',
    'DC':'District of Columbia',
    'DE':'Delaware',
    'FL':'Florida',
    'GA':'Georgia',
    'HI':'Hawaii',
    'IA':'Iowa',
    'ID':'Idaho',
    'IL':'Illinois',
    'IN':'Indiana',
    'KS':'Kansas',
    'KY':'Kentucky',
    'LA':'Louisiana',
    'MA':'Massachusetts',
    'MD':'Maryland',
    'ME':'Maine',
    'MI':'Michigan',
    'MN':'Minnesota',
    'MO':'Missouri',
    'MS':'Mississippi',
    'MT':'Montana',
    'NC':'North Carolina',
    'ND':'North Dakota',
    'NE':'Nebraska',
    'NH':'New Hampshire',
    'NJ':'New Jersey',
    'NM':'New Mexico',
    'NV':'Nevada',
    'NY':'New York',
    'OH':'Ohio',
    'OK':'Oklahoma',
    'OR':'Oregon',
    'PA':'Pennsylvania',
    'RI':'Rhode Island',
    'SC':'South Carolina',
    'SD':'South Dakota',
    'TN':'Tennessee',
    'TX':'Texas',
    'UT':'Utah',
    'VA':'Virginia',
    'VT':'Vermont',
    'WA':'Washington',
    'WI':'Wisconsin',
    'WV':'West Virginia',
    'WY':'Wyoming'
}

In [57]:
combined = pd.concat([q19_w, q20_w, q21_w, q22_w], axis = 1)
combined.columns = ['q19', 'q20', 'q21', 'q22']
combined.reset_index(inplace = True)
combined['sitecode'] = combined['sitecode'].replace(states)
combined.head()

     sitecode       q19       q20       q21       q22
0      Alaska  0.088739  0.118493  0.053359  0.055103
1     Alabama  0.103305  0.118160  0.068489  0.080397
2    Arkansas  0.126097  0.159439  0.074391  0.092193
3     Arizona  0.095725  0.118467  0.052761  0.047463
4  California  0.070472  0.147265  0.069576  0.045308

In [58]:
yrbs_by_state_str = dataloc + "yrbs_by_state.csv"

combined.to_csv(yrbs_by_state_str)

In [59]:
# merge in public health data 

policy = pd.read_csv(manualloc + "Sex_Ed_Policy.csv")

In [60]:
merged = pd.merge(policy, combined, left_on='State', right_on='sitecode')

## Merging in data and sorting

In [61]:
merged.sort_values('q19').head(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
39,Vermont,1.0,NaN,"Cover, limited",NaN,1.0,Vermont,0.060837,NaN,0.067361,0.050501
40,Virginia,1.0,1.0,"Cover, limited",NaN,1.0,Virginia,0.060961,0.094294,0.043271,0.059697
25,New Hampshire,1.0,NaN,NaN,NaN,1.0,New Hampshire,0.061750,0.097810,0.062378,0.050522
5,Colorado,NaN,1.0,"Cover, expansive",NaN,1.0,Colorado,0.066484,NaN,NaN,0.055631
42,Wisconsin,NaN,NaN,NaN,Most Restrictive (Our Interpretation),2.0,Wisconsin,0.070298,NaN,0.074506,0.053452
4,California,1.0,NaN,"Cover, expansive",NaN,1.0,California,0.070472,0.147265,0.069576,0.045308
28,New York,NaN,NaN,NaN,NaN,99.0,New York,0.070510,0.120101,0.064129,0.064694
30,North Dakota,1.0,NaN,NaN,Restrictive,1.0,North Dakota,0.074448,0.089410,NaN,0.057627
32,Pennsylvania,NaN,NaN,NaN,Restrictive,99.0,Pennsylvania,0.076079,0.102152,0.045446,0.047655
8,Florida,NaN,NaN,NaN,Restrictive,2.0,Florida,0.076231,0.103470,0.060046,0.065400
31,Oklahoma,NaN,1.0,NaN,Most Restrictive,2.0,Oklahoma,0.077039,0.115966,0.060205,0.056621
33,Rhode Island,1.0,1.0,"Cover, expansive",NaN,2.0,Rhode Island,0.077438,NaN,0.065398,0.052181
7,Delaware,1.0,1.0,NaN,NaN,2.0,Delaware,0.077772,0.076865,0.054224,0.062027
6,Connecticut,NaN,NaN,"Cover, expansive",NaN,1.0,Connecticut,0.078932,NaN,0.068428,0.048496
14,Kansas,1.0,NaN,NaN,Restrictive,NaN,Kansas,0.081662,0.117561,0.061007,0.047388

In [62]:
merged.sort_values('q19').tail(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
21,Missouri,NaN,1.0,"Cover, expansive",Most Restrictive,2.0,Missouri,0.089921,NaN,NaN,0.070042
18,Maryland,1.0,1.0,"Cover, expansive",NaN,1.0,Maryland,0.090582,0.108496,0.060044,0.065359
41,West Virginia,1.0,NaN,"Cover, limited",Most Restrictive (Our Interpretation),1.0,West Virginia,0.090981,0.112639,0.060528,0.074055
22,Montana,1.0,NaN,NaN,NaN,NaN,Montana,0.093221,0.104706,0.058809,0.055327
12,Illinois,NaN,1.0,"Cover, expansive",NaN,1.0,Illinois,0.093460,0.125979,0.063451,0.068152
19,Michigan,NaN,NaN,NaN,NaN,2.0,Michigan,0.093645,0.115712,0.059777,0.053470
20,Mississippi,1.0,NaN,NaN,Restrictive,2.0,Mississippi,0.094206,0.113276,0.074537,0.079215
15,Kentucky,1.0,NaN,NaN,Restrictive,2.0,Kentucky,0.095384,0.092898,0.060141,0.062604
2,Arizona,NaN,NaN,NaN,Restrictive,2.0,Arizona,0.095725,0.118467,0.052761,0.047463
34,South Carolina,1.0,NaN,"Cover, limited",Very Restrictive,2.0,South Carolina,0.100354,0.130074,0.057335,0.063336
0,Alabama,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Alabama,0.103305,0.118160,0.068489,0.080397
43,Wyoming,NaN,NaN,NaN,NaN,NaN,Wyoming,0.108204,NaN,0.069236,0.068964
9,Georgia,1.0,NaN,NaN,Restrictive,2.0,Georgia,0.108205,0.118705,0.039138,0.060728
3,Arkansas,NaN,NaN,NaN,Most Restrictive,2.0,Arkansas,0.126097,0.159439,0.074391,0.092193
16,Louisiana,NaN,NaN,NaN,Restrictive,2.0,Louisiana,NaN,NaN,0.116668,0.105210

In [63]:
merged.sort_values('q20').head(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
7,Delaware,1.0,1.0,NaN,NaN,2.0,Delaware,0.077772,0.076865,0.054224,0.062027
30,North Dakota,1.0,NaN,NaN,Restrictive,1.0,North Dakota,0.074448,0.089410,NaN,0.057627
15,Kentucky,1.0,NaN,NaN,Restrictive,2.0,Kentucky,0.095384,0.092898,0.060141,0.062604
40,Virginia,1.0,1.0,"Cover, limited",NaN,1.0,Virginia,0.060961,0.094294,0.043271,0.059697
25,New Hampshire,1.0,NaN,NaN,NaN,1.0,New Hampshire,0.061750,0.097810,0.062378,0.050522
37,Texas,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Texas,0.089309,0.101820,0.052581,0.059155
32,Pennsylvania,NaN,NaN,NaN,Restrictive,99.0,Pennsylvania,0.076079,0.102152,0.045446,0.047655
24,Nevada,1.0,NaN,NaN,NaN,NaN,Nevada,0.087844,0.103090,0.071227,0.058463
8,Florida,NaN,NaN,NaN,Restrictive,2.0,Florida,0.076231,0.103470,0.060046,0.065400
22,Montana,1.0,NaN,NaN,NaN,NaN,Montana,0.093221,0.104706,0.058809,0.055327
27,New Mexico,1.0,NaN,"Cover, expansive",NaN,99.0,New Mexico,0.084132,0.106760,0.066082,0.064365
18,Maryland,1.0,1.0,"Cover, expansive",NaN,1.0,Maryland,0.090582,0.108496,0.060044,0.065359
23,Nebraska,NaN,NaN,NaN,Restrictive,NaN,Nebraska,0.086835,0.108877,0.055515,0.048238
26,New Jersey,1.0,1.0,"Cover, expansive",NaN,2.0,New Jersey,0.085491,0.109011,NaN,0.045446
13,Iowa,1.0,NaN,NaN,Restrictive,NaN,Iowa,0.083151,0.109482,0.045162,0.046438

In [64]:
merged.sort_values('q20').tail(25)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
19,Michigan,NaN,NaN,NaN,NaN,2.0,Michigan,0.093645,0.115712,0.059777,0.053470
31,Oklahoma,NaN,1.0,NaN,Most Restrictive,2.0,Oklahoma,0.077039,0.115966,0.060205,0.056621
14,Kansas,1.0,NaN,NaN,Restrictive,NaN,Kansas,0.081662,0.117561,0.061007,0.047388
29,North Carolina,1.0,NaN,"Cover, expansive",NaN,2.0,North Carolina,0.086816,0.118026,0.055298,0.058575
0,Alabama,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Alabama,0.103305,0.118160,0.068489,0.080397
2,Arizona,NaN,NaN,NaN,Restrictive,2.0,Arizona,0.095725,0.118467,0.052761,0.047463
1,Alaska,NaN,NaN,NaN,NaN,NaN,Alaska,0.088739,0.118493,0.053359,0.055103
9,Georgia,1.0,NaN,NaN,Restrictive,2.0,Georgia,0.108205,0.118705,0.039138,0.060728
28,New York,NaN,NaN,NaN,NaN,99.0,New York,0.070510,0.120101,0.064129,0.064694
12,Illinois,NaN,1.0,"Cover, expansive",NaN,1.0,Illinois,0.093460,0.125979,0.063451,0.068152
34,South Carolina,1.0,NaN,"Cover, limited",Very Restrictive,2.0,South Carolina,0.100354,0.130074,0.057335,0.063336
11,Idaho,NaN,NaN,NaN,Restrictive,2.0,Idaho,0.088660,0.139820,0.083286,0.054789
4,California,1.0,NaN,"Cover, expansive",NaN,1.0,California,0.070472,0.147265,0.069576,0.045308
38,Utah,1.0,NaN,NaN,Restrictive,2.0,Utah,0.085446,0.158778,0.063300,0.046919
3,Arkansas,NaN,NaN,NaN,Most Restrictive,2.0,Arkansas,0.126097,0.159439,0.074391,0.092193
5,Colorado,NaN,1.0,"Cover, expansive",NaN,1.0,Colorado,0.066484,NaN,NaN,0.055631
6,Connecticut,NaN,NaN,"Cover, expansive",NaN,1.0,Connecticut,0.078932,NaN,0.068428,0.048496
16,Louisiana,NaN,NaN,NaN,Restrictive,2.0,Louisiana,NaN,NaN,0.116668,0.105210
17,Maine,1.0,1.0,"Cover, expansive",NaN,2.0,Maine,0.082297,NaN,NaN,0.057048
21,Missouri,NaN,1.0,"Cover, expansive",Most Restrictive,2.0,Missouri,0.089921,NaN,NaN,0.070042
33,Rhode Island,1.0,1.0,"Cover, expansive",NaN,2.0,Rhode Island,0.077438,NaN,0.065398,0.052181
36,Tennessee,1.0,NaN,NaN,Very Restrictive,2.0,Tennessee,0.083678,NaN,0.084365,0.076593
39,Vermont,1.0,NaN,"Cover, limited",NaN,1.0,Vermont,0.060837,NaN,0.067361,0.050501
42,Wisconsin,NaN,NaN,NaN,Most Restrictive (Our Interpretation),2.0,Wisconsin,0.070298,NaN,0.074506,0.053452
43,Wyoming,NaN,NaN,NaN,NaN,NaN,Wyoming,0.108204,NaN,0.069236,0.068964

In [65]:
merged.sort_values('q21').head(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
9,Georgia,1.0,NaN,NaN,Restrictive,2.0,Georgia,0.108205,0.118705,0.039138,0.060728
40,Virginia,1.0,1.0,"Cover, limited",NaN,1.0,Virginia,0.060961,0.094294,0.043271,0.059697
13,Iowa,1.0,NaN,NaN,Restrictive,NaN,Iowa,0.083151,0.109482,0.045162,0.046438
32,Pennsylvania,NaN,NaN,NaN,Restrictive,99.0,Pennsylvania,0.076079,0.102152,0.045446,0.047655
37,Texas,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Texas,0.089309,0.101820,0.052581,0.059155
2,Arizona,NaN,NaN,NaN,Restrictive,2.0,Arizona,0.095725,0.118467,0.052761,0.047463
1,Alaska,NaN,NaN,NaN,NaN,NaN,Alaska,0.088739,0.118493,0.053359,0.055103
7,Delaware,1.0,1.0,NaN,NaN,2.0,Delaware,0.077772,0.076865,0.054224,0.062027
35,South Dakota,NaN,NaN,NaN,Most Restrictive,1.0,South Dakota,0.083053,0.110175,0.054552,0.049978
29,North Carolina,1.0,NaN,"Cover, expansive",NaN,2.0,North Carolina,0.086816,0.118026,0.055298,0.058575
23,Nebraska,NaN,NaN,NaN,Restrictive,NaN,Nebraska,0.086835,0.108877,0.055515,0.048238
34,South Carolina,1.0,NaN,"Cover, limited",Very Restrictive,2.0,South Carolina,0.100354,0.130074,0.057335,0.063336
22,Montana,1.0,NaN,NaN,NaN,NaN,Montana,0.093221,0.104706,0.058809,0.055327
19,Michigan,NaN,NaN,NaN,NaN,2.0,Michigan,0.093645,0.115712,0.059777,0.053470
18,Maryland,1.0,1.0,"Cover, expansive",NaN,1.0,Maryland,0.090582,0.108496,0.060044,0.065359

In [69]:
merged.sort_values('q21').tail(20)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
28,New York,NaN,NaN,NaN,NaN,99.0,New York,0.070510,0.120101,0.064129,0.064694
33,Rhode Island,1.0,1.0,"Cover, expansive",NaN,2.0,Rhode Island,0.077438,NaN,0.065398,0.052181
27,New Mexico,1.0,NaN,"Cover, expansive",NaN,99.0,New Mexico,0.084132,0.106760,0.066082,0.064365
39,Vermont,1.0,NaN,"Cover, limited",NaN,1.0,Vermont,0.060837,NaN,0.067361,0.050501
6,Connecticut,NaN,NaN,"Cover, expansive",NaN,1.0,Connecticut,0.078932,NaN,0.068428,0.048496
0,Alabama,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Alabama,0.103305,0.118160,0.068489,0.080397
43,Wyoming,NaN,NaN,NaN,NaN,NaN,Wyoming,0.108204,NaN,0.069236,0.068964
4,California,1.0,NaN,"Cover, expansive",NaN,1.0,California,0.070472,0.147265,0.069576,0.045308
24,Nevada,1.0,NaN,NaN,NaN,NaN,Nevada,0.087844,0.103090,0.071227,0.058463
3,Arkansas,NaN,NaN,NaN,Most Restrictive,2.0,Arkansas,0.126097,0.159439,0.074391,0.092193
42,Wisconsin,NaN,NaN,NaN,Most Restrictive (Our Interpretation),2.0,Wisconsin,0.070298,NaN,0.074506,0.053452
20,Mississippi,1.0,NaN,NaN,Restrictive,2.0,Mississippi,0.094206,0.113276,0.074537,0.079215
11,Idaho,NaN,NaN,NaN,Restrictive,2.0,Idaho,0.088660,0.139820,0.083286,0.054789
36,Tennessee,1.0,NaN,NaN,Very Restrictive,2.0,Tennessee,0.083678,NaN,0.084365,0.076593
16,Louisiana,NaN,NaN,NaN,Restrictive,2.0,Louisiana,NaN,NaN,0.116668,0.105210
5,Colorado,NaN,1.0,"Cover, expansive",NaN,1.0,Colorado,0.066484,NaN,NaN,0.055631
17,Maine,1.0,1.0,"Cover, expansive",NaN,2.0,Maine,0.082297,NaN,NaN,0.057048
21,Missouri,NaN,1.0,"Cover, expansive",Most Restrictive,2.0,Missouri,0.089921,NaN,NaN,0.070042
26,New Jersey,1.0,1.0,"Cover, expansive",NaN,2.0,New Jersey,0.085491,0.109011,NaN,0.045446
30,North Dakota,1.0,NaN,NaN,Restrictive,1.0,North Dakota,0.074448,0.089410,NaN,0.057627

In [67]:
merged.sort_values('q22').head(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
4,California,1.0,NaN,"Cover, expansive",NaN,1.0,California,0.070472,0.147265,0.069576,0.045308
26,New Jersey,1.0,1.0,"Cover, expansive",NaN,2.0,New Jersey,0.085491,0.109011,NaN,0.045446
13,Iowa,1.0,NaN,NaN,Restrictive,NaN,Iowa,0.083151,0.109482,0.045162,0.046438
38,Utah,1.0,NaN,NaN,Restrictive,2.0,Utah,0.085446,0.158778,0.063300,0.046919
14,Kansas,1.0,NaN,NaN,Restrictive,NaN,Kansas,0.081662,0.117561,0.061007,0.047388
2,Arizona,NaN,NaN,NaN,Restrictive,2.0,Arizona,0.095725,0.118467,0.052761,0.047463
32,Pennsylvania,NaN,NaN,NaN,Restrictive,99.0,Pennsylvania,0.076079,0.102152,0.045446,0.047655
23,Nebraska,NaN,NaN,NaN,Restrictive,NaN,Nebraska,0.086835,0.108877,0.055515,0.048238
6,Connecticut,NaN,NaN,"Cover, expansive",NaN,1.0,Connecticut,0.078932,NaN,0.068428,0.048496
35,South Dakota,NaN,NaN,NaN,Most Restrictive,1.0,South Dakota,0.083053,0.110175,0.054552,0.049978
39,Vermont,1.0,NaN,"Cover, limited",NaN,1.0,Vermont,0.060837,NaN,0.067361,0.050501
25,New Hampshire,1.0,NaN,NaN,NaN,1.0,New Hampshire,0.061750,0.097810,0.062378,0.050522
33,Rhode Island,1.0,1.0,"Cover, expansive",NaN,2.0,Rhode Island,0.077438,NaN,0.065398,0.052181
42,Wisconsin,NaN,NaN,NaN,Most Restrictive (Our Interpretation),2.0,Wisconsin,0.070298,NaN,0.074506,0.053452
19,Michigan,NaN,NaN,NaN,NaN,2.0,Michigan,0.093645,0.115712,0.059777,0.053470

In [68]:
merged.sort_values('q22').tail(15)

,State,SIECUS sex-ed req EDITED,SIECUS consent req EDITED,SIECUS contraception req,Abortion,Abstinence (SIECUS),sitecode,q19,q20,q21,q22
15,Kentucky,1.0,NaN,NaN,Restrictive,2.0,Kentucky,0.095384,0.092898,0.060141,0.062604
34,South Carolina,1.0,NaN,"Cover, limited",Very Restrictive,2.0,South Carolina,0.100354,0.130074,0.057335,0.063336
27,New Mexico,1.0,NaN,"Cover, expansive",NaN,99.0,New Mexico,0.084132,0.106760,0.066082,0.064365
28,New York,NaN,NaN,NaN,NaN,99.0,New York,0.070510,0.120101,0.064129,0.064694
18,Maryland,1.0,1.0,"Cover, expansive",NaN,1.0,Maryland,0.090582,0.108496,0.060044,0.065359
8,Florida,NaN,NaN,NaN,Restrictive,2.0,Florida,0.076231,0.103470,0.060046,0.065400
12,Illinois,NaN,1.0,"Cover, expansive",NaN,1.0,Illinois,0.093460,0.125979,0.063451,0.068152
43,Wyoming,NaN,NaN,NaN,NaN,NaN,Wyoming,0.108204,NaN,0.069236,0.068964
21,Missouri,NaN,1.0,"Cover, expansive",Most Restrictive,2.0,Missouri,0.089921,NaN,NaN,0.070042
41,West Virginia,1.0,NaN,"Cover, limited",Most Restrictive (Our Interpretation),1.0,West Virginia,0.090981,0.112639,0.060528,0.074055
36,Tennessee,1.0,NaN,NaN,Very Restrictive,2.0,Tennessee,0.083678,NaN,0.084365,0.076593
20,Mississippi,1.0,NaN,NaN,Restrictive,2.0,Mississippi,0.094206,0.113276,0.074537,0.079215
0,Alabama,NaN,NaN,"Cover, limited",Most Restrictive,2.0,Alabama,0.103305,0.118160,0.068489,0.080397
3,Arkansas,NaN,NaN,NaN,Most Restrictive,2.0,Arkansas,0.126097,0.159439,0.074391,0.092193
16,Louisiana,NaN,NaN,NaN,Restrictive,2.0,Louisiana,NaN,NaN,0.116668,0.105210